### ISSUE TITLE
Can't seek to the same location twice

### ISSUE THREAD

**Issue by will-hart** [cloudflare/stream-react#14]
Seeking to the same timestamp by setting `currentTime` only works the first time.

**Reproduction:**

```typescript
const Player = ({url}) => {
  const [seekTime, setSeekTime] = React.useState<number>(0)

  return (
    <>
      <button onClick={() => setSeekTime(33)}>Seek</button>
      <Stream src={url} currentTime={seekTime} />
    </>
  )
}
```

Clicking the button the first time seeks, but clicking it a second time (with the video playing) has no effect. I can work around this by setting the currentTime twice (delaying the second using a timeout): 

```typescript
const seek = React.useCallback(
  (seekTo: number) => {
    setSeekTime(undefined)
    setTimeout(() => setSeekTime(seekTo), 1)
  },
  [setSeekTime]
)
```

---

As a side note, are the notes for the `currentTime` prop correct? It says

>  Returns the current playback time in seconds.

which I don't think is right?

**Comment by third774** [comment]
Hey there! As you've noted, the `currentTime` prop does only seek when changed, and is a limitation of the prop API for this since we cannot distinguish between re-renders that should *not* seek from re-renders that *should* seek when the `currentTime` has not changed.

A better approach here is to use the `streamRef` to get access to the actual `stream` element and set the `currentTime` property on it, which will always trigger seeking.

[Here's an example](https://codesandbox.io/s/epic-curran-cbsl2?file=/src/App.tsx)

It looks like `streamRef` has an issue with the typings, and we need to add some docs to the README. Working on updating these!

Lastly, regarding the notes for the `currentTime` — thanks for mentioning! Looks like this was copied over from docs and isn't quite accurate in the context of props. Will update this as well.

Thanks for reporting! 😃

**Comment by will-hart** [comment]
Awesome, thanks for the detailed reply!

It seems this could be closed, or do you want to leave it open to track the documentation changes?

**Comment by third774** [comment]
I'll close it out when the `streamRef` types are fixed and docs are updated!

**Comment by third774** [comment]
Published a new version that addresses the `streamRef` type definition and adds it to the documented props.

[Example can be seen here](https://codesandbox.io/s/sleepy-kapitsa-wt0sj?file=/src/App.tsx)

Thanks again!
