### ISSUE TITLE
'document' is not defined when importing Stream in Server Side Rendering

### ISSUE THREAD

**Issue by tekephillips** [cloudflare/stream-react#18]
Hey everyone,

I'm unable to server-side render any apps that imports Stream because an error gets thrown: `document is not defined`.  Looking into the source code, there's a line referring to global namespace, document, with no validation to check if global namespace document exists:
`var scriptLocation = "https://embed.videodelivery.net/embed/r4xu.fla9.latest.js";
var streamScript = /*#__PURE__*/document.querySelector("script[src=\"" + scriptLocation + "\"]");`

Ideally, I'd like to use the react module in my codebase as it is cleaner, but do you recommend I use the <iframe> code snippet in the app code instead of this module for SSR compatibility?  Thanks in advance

**Comment by leftyfl1p** [comment]
Same issue I'm seeing. Wanted to display a video on the background of our landing page, signed up for cloudflare pages, video won't load on safari because cloudflare page servers don't support byte-range requests, so I signed up for cloudflare stream, react component doesn't support SSR and can't size the video properly when its nested in an iframe. Not a great first impression, honestly.

**Comment by third774** [comment]
This should be resolved with `v0.3.0`! Thanks for reporting!
