### ISSUE TITLE
Video thumbnails don't load with preload "none"

### ISSUE THREAD

**Issue by santsys** [cloudflare/stream-react#33]
I've noticed that I am unable to get video thumbnails to load without having the preload property set to at least `metadata`. With the metadata value, the thumbnail is loaded but a chunk of the video is also loaded causing unnecessary loading.

When using an iframe based include, this does not appear to happen. See the code below. This loads the thumbnail, and does not load any of the video until the user clicks play.

Is there a way to get this result using the stream component?

```
<div style={{ position: 'relative', paddingTop: '56.25%' }}>
        <iframe
          src={
            'https://iframe.videodelivery.net/' +
            props.cfStreamId +
            '?preload=none'
          }
          title='Video'
          style={{
            border: 'none',
            position: 'absolute',
            top: '0',
            height: '100%',
            width: '100%',
            left: '0',
          }}
          allow='accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture; fullscreen'
        ></iframe>
</div>
```

Thank you!

**Comment by third774** [comment]
It looks like `preload="none"` is not sending the video's aspect ratio because the video's metadata has not loaded yet.

If you'd like to manage the styles yourself, you can set `responsive={false}` which will disable the inline styles that are normally applied, and style the `Stream` element (and its inner iframe) with the `className` prop.

https://codesandbox.io/s/kind-allen-nyi8b?file=/src/App.js

We'll take a look at making this less of a sharp edge — thanks for reporting!

**Comment by third774** [comment]
This is resolved! The Stream player will now report dimensions of the video to the host page regardless of whether or not any video data has been loaded.

**Comment by santsys** [comment]
@third774 YES!? Is there a version rolling out for this or is it something in the back end of the stream service??

**Comment by third774** [comment]
@santsys the fix should be live and working everywhere, no new version of this package needed! 😃

**Comment by santsys** [comment]
@third774 Can confirm. Seems to be working great. THANK YOU!
