### ISSUE TITLE
SVG play icon not consistently displaying on iOS

### ISSUE THREAD

**Issue by hdehal** [cloudflare/stream-react#40]
Hey CF team – we're using `@cloudflare/stream-react` and we're seeing odd behavior on a handful of iOS/iPhone devices (we've tested a few).

The SVG play icon does not consistently load on iOS. When testing on other devices, e.g. Chrome w/ iOS emulator, it loads just fine. Not sure if this is an SVG rendering bug, but I did notice if I leave Safari iOS for a 10-15 seconds and come back, it eventually displays (long after initial pageload).

Here is a link to an example for easy repro:
https://get.doordash.com/en-us/products/merchant-portal#4SQyxBHt6fZliIluzKZOQw

![image](https://user-images.githubusercontent.com/21130143/137855830-e249418f-771d-463c-bcb8-d52140a2ec1e.png)

![Image from iOS](https://user-images.githubusercontent.com/21130143/137855225-d4f7d296-d268-4c16-bfe1-8d386e5695da.png)

![image](https://user-images.githubusercontent.com/21130143/137855540-5b09648f-2437-4c82-b461-77ad879caafb.png)

Thanks in advance!

**Comment by third774** [comment]
Thanks for reporting! We'll dig into this and report back!

**Comment by third774** [comment]
It looks like this might be the result of a bug in the webkit rendering engine. I've put together a reduced test case in codepen where I can reliably reproduce the issue:

1. Open this link in Safari: [https://codepen.io/third774/pen/bGremBW?editors=1100](https://codepen.io/third774/pen/bGremBW?editors=1100)
2. Resize the window vertically until the button is elliptical instead of circular
3. Refresh the page and it will go back to being circular

In Chrome and Firefox, resizing the window vertically does the following:
1. Changes the height of the button, which
2. Changes the height of the SVG icon which
3. Changes the width of the SVG icon which
4. Changes the width of the button

Effect #4 here does not appear to be happening in Safari.

To fix the issue we've changed the big play button to scale the icon directly such that resizing the window vertically:
1. Changes the height of the SVG which
2. Changes the width of the SVG which
3. Changes both height & width of the button

I'm still looking to see if this bug has already been reported in webkit, but haven't had any luck finding it yet. Thanks again for reporting!
