### ISSUE TITLE
Get back the player from videojs

### ISSUE THREAD

**Issue by bluebeel** [cloudflare/stream-react#5]
Hello,

I wanted to use your stream component and extends it with some plugin.
To do that, I would need to get access to the player object.
With the props streamRef, I know I can get the dom element but I don't see how i could get him then use him afterward.

Thanks for the component by te way.

**Comment by renandincer** [comment]
Hey @bluebeel! Hope you're finding the component useful :)

We only support interacting with the stream component using props. Feel free to directly access the DOM element and load the plugin for temporarly, but we make breaking changes under the component regularly. Modifying the dom element might cause unexpected behavior for your users in the future.

- If you could share the plugin you plan to use, we can see if there is a way to achieve your goal with the props already provided.
- Alternatively, if you feel comfortable with using a third party player, you can also use videojs directly with Stream by using DASH or HLS manifests provided by Stream. Click on "View as JSON" button in the Stream dashboard to access these URLs.

**Comment by bluebeel** [comment]
Thanks @renandincer for this quick answer.

I wanted to add a plugin to share videos for example and the possibility to activate or deactivate a component of the videojs controlBar such as the small player button, the PiP button or deactivate the playrate selector button.
So I was looking for a way to access the videojs object for that.

**Comment by renandincer** [comment]
Oh got it!

We don't support UI customization like you suggested yet. Activating & deactivating certain features is a good idea though.

If you're looking for a quick solution suggest putting the share button outside of the video like YouTube does. One could say only the settings about this particular video view (like playback speed or fullscreen) should live in the player while the share button to the webpage where the video is also located captures a wider context (the entire webpage, perhaps comments, title and related content) that can be shared.

![image](https://user-images.githubusercontent.com/1429100/87383054-4f313500-c54d-11ea-9e0f-fd111432738e.png)

Otherwise, I suggest using a different player as we're still working on player customization details for Stream. Perhaps Videojs with the plugin you suggested is a good idea. If you choose to go this path, you can still use Stream with the DASH and HLS URLs.

Let us know which path you end up going - perhaps others can also benefit from this discussion in the future. I'll update this thread when Stream player supports more robust configuration and customization options.
